name: Build and Deploy to Shopify

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        with:
          path: .

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: 📦 Install dependencies
        run: |
          cd src
          npm install

      - name: 🛠 Compile assets with Gulp
        run: |
          cd src
          npx gulp build

      - name: 📤 Commit compiled assets and other changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "🔧 Auto-compile assets and push theme updates" || echo "No changes to commit"
          git push origin main