name: Build and Deploy to Shopify

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        with:
          path: .

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: 📦 Install dependencies
        run: |
          cd src
          npm install

      - name: 🛠 Compile assets with Gulp
        run: |
          cd src
          npx gulp build
          cd ..
          git add assets/

      - name: 📤 Commit compiled assets and other changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          echo "Remote URL before: $(git remote get-url origin)"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          echo "Remote URL after: $(git remote get-url origin)"
          git add -f assets/*.min.css assets/*.min.js
          git commit -m "🔧 Auto-compile assets and push theme updates" || echo "No changes to commit"
          git push origin main